### ISSUE TITLE
Allow set Fargate Platform Version

### ISSUE THREAD

**Issue by RomanDanyk** [uktrade/fargatespawner#16]
The [AWS Fargate Platform Version](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/platform_versions.html) `1.4.0` supports using Amazon EFS file system volumes for persistent task storage. However, the `LATEST` version still uses the `1.3.0` platform version.
In the same time [RunTask ECS API method](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RunTask.html) supports the `platformVersion` parameter.
It would be nice to have an option for selecting the desired platform version.

**Comment by michalc** [comment]
This should now be possible with the latest version of the spawner that allows the setting of any RunTask parameters. The significant change was done in https://github.com/uktrade/fargatespawner/commit/72b20163825af557f401268a9f7108174e2dd83b
