### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by JasonIamAUnixAdmin** [uktrade/fargatespawner#5]
I am working on getting this setup for our current notebook setup. In the readme to use rolls for ECS auth this is what is written
`from jupters3 import FargateSpawnerECSRoleAuthentication`

Should that be 
`from fargatespawner import FargateSpawnerECSRoleAuthentication`

I can do a PR if so.
Thanks

**Comment by michalc** [comment]
Hi @JasonIamAUnixAdmin 

Thanks for the report, and apologies for the delay in getting back to you. Yes, you're right in the that README is wrong here. A PR fixing this would be very much appreciated.

Thanks,

Michal

**Comment by michalc** [comment]
Fixed by https://github.com/uktrade/fargatespawner/pull/6
